apiVersion: build.openshift.io/v1
kind: BuildConfig
metadata:
  labels:
    build: s2i-scipy-notebook
  name: s2i-scipy-custom-notebook
spec:
  output:
    to:
      kind: ImageStreamTag
      name: s2i-scipy-custom-notebook:latest
  source:
    git:
      ref: main
      uri: 'https://github.com/luisarizmendi/s2i-custom-data-science-notebook'
    type: Git
  strategy:
    type: Source
    sourceStrategy:
      from:
        kind: ImageStreamTag
        name: s2i-generic-data-science-notebook:v0.0.4
      env: []
  triggers:
    - type: ImageChange
      imageChange: {}
    - type: ConfigChange